version: 2

updates:
  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 15
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "github_actions"

  # pnpm Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 15
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    labels:
      - "dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Python Dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 15
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "python"
